### ISSUE TITLE
Graphical bug in top windows on intel integrated GPU

### ISSUE THREAD

**Issue by samuelstjean** [scilus/fibernavigator#166]
The small windows at the top displaying the view of each plane have some small graphical bugs under linux. They display the background as a checkerboard instead of the actual color of the anatomy, but it doesn't affect the main 3D window and seems mostly cosmetic.

Not sure about the libraries version used for building (we pulled the latest code from master on december 19-20), I think it was on ubuntu 13.10 and glew 1.8. Ask Elef and his new laptop for more details.

**Comment by samuelstjean** [comment]
Tried on my personal laptio, with also integrated graphics/newer drivers, and it works. So it's a quirk with some integrated cards which is now fixed I'd say.

**Comment by jchoude** [comment]
Yes, we generally do not recommend integrated graphics.
