### ISSUE TITLE
error during building

### ISSUE THREAD

**Issue by TBaker76** [scilus/fibernavigator#205]
Hi,

I would like to use fibernavigator with ubunto. I have followed directions, and have all dependencies up to date. However, I receive this error message when trying to load it

 CMake Warning (dev) in CMakeLists.txt:
   Syntax Warning in cmake code at

     /home/travis/Downloads/fibernavigator/src/CMakeLists.txt:57:53

   Argument not separated from preceding token by whitespace.
 This warning is for project developers.  Use -Wno-dev to suppress it.

Thanks for your help
Travis

**Comment by jchoude** [comment]
Hi Travis,

sorry for the delay in replying.

Normally, this shouldn't affect your build, as it is just a warning for the developers. Did you still succeed in compiling the code, or not?

Also, which version of Cmake are you using? And which release of Ubuntu?

Finally, just to make sure, are you trying to compile the rtfmri-coloring-feature branch, or the master one?

Cheers!

--
Jean-Christophe

**Comment by TBaker76** [comment]
Thanks for your help!

I could not compile the code. There were errors, so I assumed it had to do
with the error I noted.

info requested:

cmake version: cmake version 2.8.12.2
Ubuntu version: 14.04
compile: I was trying the master version. should I try to compile the
rtFMRI....?

Cheers,
Travis

**Comment by TBaker76** [comment]
FYI-when I try the last step, "make", these are the errors I get

[  1%] Building CXX object CMakeFiles/fibernavigator.dir/main.cpp.o
/home/travis/Downloads/fibernavigator/src/main.cpp:49:1: error: cannot
convert ‘const wchar_t*’ to ‘const char*’ in initialization
 };
 ^
/home/travis/Downloads/fibernavigator/src/main.cpp:49:1: error: cannot
convert ‘const wchar_t*’ to ‘const char*’ in initialization
/home/travis/Downloads/fibernavigator/src/main.cpp:49:1: error: cannot
convert ‘const wchar_t*’ to ‘const char*’ in initialization
/home/travis/Downloads/fibernavigator/src/main.cpp:49:1: error: cannot
convert ‘const wchar_t*’ to ‘const char*’ in initialization
/home/travis/Downloads/fibernavigator/src/main.cpp:49:1: error: cannot
convert ‘const wchar_t*’ to ‘const char*’ in initialization
/home/travis/Downloads/fibernavigator/src/main.cpp:49:1: error: cannot
convert ‘const wchar_t*’ to ‘const char*’ in initialization
/home/travis/Downloads/fibernavigator/src/main.cpp:49:1: error: cannot
convert ‘const wchar_t*’ to ‘const char*’ in initialization
/home/travis/Downloads/fibernavigator/src/main.cpp:49:1: error: cannot
convert ‘const wchar_t*’ to ‘const char*’ in initialization
/home/travis/Downloads/fibernavigator/src/main.cpp:49:1: error: cannot
convert ‘const wchar_t*’ to ‘const char*’ in initialization
/home/travis/Downloads/fibernavigator/src/main.cpp:49:1: error: cannot
convert ‘const wchar_t*’ to ‘const char*’ in initialization
/home/travis/Downloads/fibernavigator/src/main.cpp:49:1: error: cannot
convert ‘const wchar_t*’ to ‘const char*’ in initialization
/home/travis/Downloads/fibernavigator/src/main.cpp:49:1: error: cannot
convert ‘const wchar_t*’ to ‘const char*’ in initialization
/home/travis/Downloads/fibernavigator/src/main.cpp:49:1: error: cannot
convert ‘const wchar_t*’ to ‘const char*’ in initialization
make[2]: *** [CMakeFiles/fibernavigator.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/fibernavigator.dir/all] Error 2
make: *** [all] Error 2

**Comment by jchoude** [comment]
Hey,

yes, those errors are not related to the warning you saw from the Cmake file.

If you want the the newest features (which I would recommend), you should indeed build the rtfmri-coloring-feature branch. They would also remove your current errors.

I don't know your level of familiarity with git. If you need help with setting up the correct branch, please let me know.

Also, I don't know if you are following those instructions, but they are the most up to date instructions, and should work out of the box with the rtfmri-coloring-feature branch: https://github.com/scilus/fibernavigator/wiki/Ubuntu-build-instructions

Best of luck!

**Comment by TBaker76** [comment]
Wonderful, thanks. I will try again tomorrow. Are you available for online
chat to walk me through these instructions in case I get stuck. Perhaps
tomorrow afternoon?

Are you in Montreal or Sherbrooke? I work at the MNI and Sainte-justine
Childrens, so I can also call you as well.

Thanks,
Travis

**Comment by jchoude** [comment]
Hey,

yes, I could be available, but mostly Friday.

I'm in Sherbrooke.

Cheers!

--
Jean-Christophe

**Comment by TBaker76** [comment]
Success! It worked with rtfmri-coloring-feature branch.

Thanks for your help,
Travus

**Comment by chamberm** [comment]
Envoyé de mon iPhone

**Comment by chamberm** [comment]
You could even try chamberm/master, or check the release there. It is an updated version of rt-fmri-coloring.

Max

Envoyé de mon iPhone

**Comment by TBaker76** [comment]
Thanks for your help.

I have been able to run the program fine with one subject. Basically
creating tracts between two ROIs (DLPFC and Caudate nucleus) this worked
fine for one of my subjects, but for the other two, the program keeps
crashes or stops once I add my second ROI as a VOI. Not sure what the issue
is here.

PS->>You could even try chamberm/master, or check the release there. It is
an updated version of rt-fmri-coloring.
can you send me the link to the specific version you are referring to here,
thanks:)

Thanks,
Travis

**Comment by jchoude** [comment]
Hi @TBaker76 

just a quick link on this: the master branch of scilus/fibernavigator is now updated to reflect the rtfmri-coloring-feature branch, and much more stuff. You should use the updated master now.
