### ISSUE TITLE
tracts and anatomical template doesn't mach up

### ISSUE THREAD

**Issue by MartenHF** [scilus/fibernavigator#207]
Hello,
I'm learning tractrography and trying to visualize M1-M1 tracts. 

When I load up the standard image (FMRIB58_FA_1mm.nii) and overlay tracts between M1-M1, they don't really match up. I think that these areas should be connected via callosal fibers, but these are off from the CC. If I use individual T1, it's even worse. tracts are off the brain.
I am wondering if someone can help solving my problem. 

Tracts are obtained using Mrtricx. 
Thank you for your help.

MartenHF

**Comment by jchoude** [comment]
Hi @MartenHF 

sorry for the delay. Has your problem been fixed, did you find a solution?

Please note that we have a new release available (and the master branch has been updated). See the [Releases](https://github.com/scilus/fibernavigator/releases) page for pre-built versions for OSX and Windows, or check the wiki for instructions on building on all platforms.
