### ISSUE TITLE
HARDI RTT crash on peaks that have 4th dimension > 9

### ISSUE THREAD

**Issue by mdesco** [scilus/fibernavigator#208]
Although we can load a peaks file with 4th dimension 15, "open anatomy as peaks", the HARDI RTT module crashes when we start tracking. 

Probably an easy bug to fix. 

This is a problem for our users... computing peaks from dipy or compute_fodf.py for example.

**Comment by chamberm** [comment]
It is fixed here: https://github.com/chamberm/fibernavigator/tree/magnet-tracking.

If we proceed with the merge of my branch in the upcoming days/weeks @jchoude, the fix will be transfered.

**Comment by LJWilliams** [comment]
When will the fix be merged? I am trying to use fibernavigator to view ODT from dipy constrained spherical deconvolution.

**Comment by chamberm** [comment]
Hi Lynne,

I think @jchoude is having a look, and we shall perform the merge in the upcoming week. (JC I will be back in sherb next week, we can have a look).

In the meantime, what version are you using (Windows, linux or mac?) I invite you to use the fixed branch (see releases page) https://github.com/chamberm/fibernavigator

Best,
Maxime

**Comment by jchoude** [comment]
Hi all, 

sorry, things are (as always) hectic around here... @chamberm You'll be here at least part of the week? If so, let's book a day (or part of a day) and do everything we were supposed to look at. I'll email you.

**Comment by jchoude** [comment]
Hi @LJWilliams ,

we now have updated the master branch to include a lot of fixes and new features. Can you go and give it a try to see if it works with your data?

Also, if you're using Windows or OSX, builds are available on the [Releases](https://github.com/scilus/fibernavigator/releases) page

**Comment by jchoude** [comment]
@mdesco can you retest with your dataset?

**Comment by LJWilliams** [comment]
I will do that. Thank-you.

**Comment by mdesco** [comment]
Works now!

**Comment by jchoude** [comment]
Thanks!
