### ISSUE TITLE
Installation difficulty: set the path to wx-config

### ISSUE THREAD

**Issue by haerts** [scilus/fibernavigator#209]
Hi all,

I'm having a bit of trouble installing the fibernavigator on my Ubuntu 14.04 desktop. I successfully installed all dependencies and wxWidgets3. I then cloned the rtfmri_coloring_feature branch to my computer (/home/user/programs/fibernavigator) and created a directory to build the fibernavigator (/home/user/programs/fibernavigator_build). From the latter directory, I did ccmake /home/user/programs/fibernavigator/src/, where I get this message:

CMAKE_BACKWARDS_COMPATIBILITY    2.4                                          
 CMAKE_INSTALL_PREFIX             /usr/local                                   
 FIBERNAVIGATOR_PLATFORM          Linux                                        
 GLEW_INCLUDE_PATH                /usr/include                                 
 GLEW_LIBRARY                     /usr/lib/x86_64-linux-gnu/libGLEW.so         
 wxWidgets_CONFIG_EXECUTABLE      wxWidgets_CONFIG_EXECUTABLE-NOTFOUND    

As such, my question is in which file I have to set a path, and where to. In my wxWidgets build directory, I don't have lib subdirectory, nor a config executable.

hannelore@Hannelore:~/Downloads/wxWidgets-3.0.2/build$ ls -l
total 60
drwxr-xr-x 2 hannelore hannelore  4096 Okt  6  2014 aclocal
drwxr-xr-x 3 hannelore hannelore  4096 Okt  6  2014 autoconf_prepend-include
-rw-r--r-- 1 hannelore hannelore  2324 Okt  6  2014 autogen.mk
drwxr-xr-x 3 hannelore hannelore  4096 Okt  6  2014 bakefiles
drwxr-xr-x 4 hannelore hannelore  4096 Okt  6  2014 buildbot
drwxr-xr-x 2 hannelore hannelore 12288 Okt  6  2014 msw
drwxr-xr-x 2 hannelore hannelore  4096 Okt  6  2014 os2
drwxr-xr-x 8 hannelore hannelore  4096 Okt  6  2014 osx
-rw-r--r-- 1 hannelore hannelore  1277 Okt  6  2014 README.txt
drwxr-xr-x 2 hannelore hannelore  4096 Okt  6  2014 script
drwxr-xr-x 3 hannelore hannelore  4096 Okt  6  2014 tools
-rwxr-xr-x 1 hannelore hannelore  3227 Okt  6  2014 update-setup-h
drwxr-xr-x 3 hannelore hannelore  4096 Okt  6  2014 wince

Thank you in advance!

Kind regards,
Hannelore

**Comment by chamberm** [comment]
Hi Hannelore,

Here is my path to my wxconfig_exec:
e.g.  Install directory / wxWidgets-3.0.2/wx-config

and the wxrc_exec:

 Install directory / wxWidgets-3.0.2//utils/wxrc/wxrc

should do it

**Comment by haerts** [comment]
Thanks!
