### ISSUE TITLE
Task-related fMRI and DTI combination?

### ISSUE THREAD

**Issue by dalakir** [scilus/fibernavigator#210]
Do you consider adding the option to combine the task-related fMRI and DTI instead of only the resting state fMRI? Please let me know if there is any plan for a future integration because I really liked the tool but I am currently working with task-related fMRI and DTI and it would be preferable if I did not need another tool. Thanks.

**Comment by chamberm** [comment]
Hi,

As it stands, fmri activation map issued from tasks can be opened in the fibernavigator.

We currently dont offer any preprocessing, as the focus of the tool is Visualization only. I suggest that you generate your nifti maps using Afni/fsl/etc, and register everything in the same space (i.e. Anatomical, diffusion). Then simply open your final maps for the interactive visualization of your network.

Maxime

**Comment by dalakir** [comment]
Perfect. Thank you very much for the prompt response and congratulations for your work. Keep up the great work. If you could integrate that in the future that would be the perfect tool. I will complete the preprocessing through AFNI and FLS and then use fibernavigator for the visualization. If I face any problems I will let you know. Thanks again.
