### ISSUE TITLE
Affine is now applied?

### ISSUE THREAD

**Issue by samuelstjean** [scilus/fibernavigator#212]
That's more a question than an issue, but is it the case? Seems like the flip button is now used according to the sign of the affine for the data, and I noticed that this week. Has it been there for a long time? The translation part for the fibers seems to not be used, so you can have floating fibers as the old version did (or the opposite, I never really understood the discrepancy between gab tracking and the tract querier.)

**Comment by chamberm** [comment]
There is now a fit to anat button to realign fibers that are in world space.( saving to vtk is now allowed and in world space)

**Comment by samuelstjean** [comment]
So after speaking in private

+ Affine is applied for anatomy (or at least the sign part is used to flip on the gui automatically), but not peaks or tracks.
+ The fit to anat button always apply the same matrix, so using it twice in a row is not a good idea. A bool keeping track if you need to apply the matrix or its inverse to bring stuff back would be favourable.
