### ISSUE TITLE
Wrong RTT behavior while flipping peaks

### ISSUE THREAD

**Issue by fmorency** [scilus/fibernavigator#215]
Tested on Ubuntu 14.04, commit 66c5866450b6d. Fresh build, I can reproduce this bug 100% of the time.
1. Open anat (FA)
2. Open peaks as anatomy (dipy-generated peaks)
3. Set anat and peaks in HARDI RTT tab
4. Start tracking
5. Flip peaks in X
6. Flip peaks in X back
7. Tracking should be similar to 4. but it's not

![first_time_rtt](https://cloud.githubusercontent.com/assets/1102868/16658994/6df52e7a-4436-11e6-8163-4d8d319251cf.png)
![flip_x_peaks](https://cloud.githubusercontent.com/assets/1102868/16659000/72ab2276-4436-11e6-9288-f27822e2ad0c.png)
![reflip_back_x_peaks](https://cloud.githubusercontent.com/assets/1102868/16659004/76a08a60-4436-11e6-93cd-d203e01373ff.png)

**Comment by chamberm** [comment]
A quick test would be to re-select the peaks after the flip (or de-flip). (re-click on the peak to be selected button while selection is on the peaks).

Just curious to see the behavior there

**Comment by fmorency** [comment]
It doesn't do anything.

On Thu, Jul 7, 2016 at 11:42 AM, chamberm <notifications@github.com> wrote:

> A quick test would be to re-select the peaks after the flip (or de-flip).
> (re-click on the peak to be selected button while selection is on the
> peaks).
>
> Just curious to see the behavior there
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/scilus/fibernavigator/issues/215#issuecomment-231118775>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABDUFB8afmDAQhGy90HZXfegdD9oXsC5ks5qTR53gaJpZM4JHNRb>
> .
>



-- 
Félix C. Morency, M.Sc.
Imeka
