### ISSUE TITLE
installation difficulty

### ISSUE THREAD

**Issue by vinkirk** [scilus/fibernavigator#217]
Hi,

I followed the Ubuntu build instructions and got the following error message when attempting to run fibernavigator:

Initializing OpenGL
../src/unix/glx11.cpp(50: assert "fbc" failed in wxGLContext(): invalid GLXFBConfig for OpenGL
Trace/breakpoint trap (core dumped)

Thanks for your help,

Vinny

**Comment by jchoude** [comment]
Hi Vinny,

what Ubuntu version are you using? What is your GPU? Are you trying to run this over a network?

**Comment by vinkirk** [comment]
I'm using Ubuntu 14.04 (Bash on Ubuntu on MS Windows).  When I run lspci | grep VGA, I get the following message:
pcilib: Cannot open /proc/bus/pci
lspci: Cannot find any working access method.

I am not running this over a network, just on my personal computer.  Oddly enough, I was able to open fibernavigator before, but now I am unable to.

**Comment by vinkirk** [comment]
when i run inxi -SG, i get the following error message:
![image](https://cloud.githubusercontent.com/assets/8159808/20482704/12800578-afbc-11e6-9164-368d5579bbd2.png)

I do have nvidia 367 installed though

**Comment by jchoude** [comment]
Ok. From what you say you're trying to use it through Bash on Ubuntu on MS Windows. We have never tried this.

The last time it worked, were you working on a native Ubuntu install, or through the same setup?

Also, if your video card cannot be detected, we highly doubt this will work.

**Comment by vinkirk** [comment]
Hi.  So I uninstalled Bash on Ubuntu on MS Windows, re-installed it again and installed XMing server on Windows.  Installed and built fibernavigator and the graphical interface appears now.  Thanks!

**Comment by jchoude** [comment]
Good news! Happy you got it to work. I'll close this.
