### ISSUE TITLE
BadMatch (invalid parameter attributes)

### ISSUE THREAD

**Issue by soichih** [scilus/fibernavigator#218]
Hello,  I've built fibernavigator on Ubuntu 14.04 image on a Docker container running xvfb and x11vnc server that I can access via noVNC client.

I did following to build fibernavigator
```
cd /fibernavigator
cmake src
make
```
I can start fibernavigator and do some basic things like resizing a window, flipping through the tab, etc.. but as soon as I try to load any T1 images, or simply clicking on the menu icon, the app crashes with following error message.

```
The program 'fibernavigator' received an X Window System error.
The probably reflects a bug in the program.
The error was 'BadMatch (invalid parameter attributes)'
  (Detail: serial 36382 error_code 8 request_Code 62 minor_code 0)
  ...
```
I am guessing this is due to the fact that I am running this in Xvfb.. but I can run mrview on this environment, so I think it should be possible to run  fibernavigator also.. Does the above error message mean anything to fibernvavigator developer by any chance?

**Comment by soichih** [comment]
Sorry, I've adjusted various things and problem disappeared. 

I believe the Xvfb parameter I was using was the case.

Before
`Xvfb :0 -screen 0 1200x800x16`

after
`Xvfb :0 -screen 0 1200x800x24`

**Comment by jchoude** [comment]
Happy that you fixed it. Closing.
