### ISSUE TITLE
Opening multiple files at startup

### ISSUE THREAD

**Issue by soichih** [scilus/fibernavigator#219]
I can open my T1 file by passing the image path to the command line like so..

```
./bin/fibernavigator ~/Download/t1.nii.gz
```

Now, I have 2 T1s that I'd like to compare so I tried ..

```
./bin/fibernavigator ~/Download/t1.nii.gz ~/.Download/another.t1.nii.gz
```

This resulted in opening only the first image. Is there anyway to open multiple T1s? Also, is there a way to automatically open both my T1 and .tck files that goes with it?

**Comment by jchoude** [comment]
Hi @soichih ,

there is currently no way to do any of the 2 use cases. It shouldn't be too hard to add, however. You are welcome to make a pull request to add support for it.

Also, an important note: the Fibernavigator doesn't really use the full information of the affine transformation. If you want to compare 2 T1 images to see if they are correctly aligned, the result might not be meaningful.

**Comment by soichih** [comment]
@jchoude Yes, I think it's understood that you can't do voxel-to-voxel comparision between different images. This is simply to make it easier for users to get started viewing different images. In fact, our user won't know the exact path where T1 images are stored, so it's important that we pre-open those images.

**Comment by jchoude** [comment]
Ok, I see.

Sadly, we don't currently have much free time to modify this. If you ever develop it, we will be happy to review your pull request.

**Comment by soichih** [comment]
OK, I've looked at main.cpp and discovered that it already support opening multiple T1 images - although it won't load the image unless following T1 image has the same dimension as the previous one.. :(

I didn't know this because -h option didn't work, so I've added it and sent a pull request
> https://github.com/scilus/fibernavigator/pull/220

I've also added -m option which will maximize the window on startup - this is desired for our use-case to provide a slightly better user experience.

**Comment by jchoude** [comment]
Yes, that's one of the limitations of the Fibernavigator, sadly.
