### ISSUE TITLE
segfaults if I try to load DWI image

### ISSUE THREAD

**Issue by soichih** [scilus/fibernavigator#221]
Does firbernavigator support DWI image?

It crashes (segfaults) if I try to load a sample DWI image that I have..

```
hayashis@haswell:~/git/fibernavigator/bin(master) $ mrinfo ~/Downloads/dwi.nii.gz 
************************************************
Image:               "/home/hayashis/Downloads/dwi.nii.gz"
************************************************
  Format:            NIfTI-1.1
  Dimensions:        173 x 207 x 173 x 79
  Voxel size:        1.05 x 1.05 x 1.05 x 1
  Dimension labels:  0. left->right (mm)
                     1. posterior->anterior (mm)
                     2. inferior->superior (mm)
                     3. undefined (?)
  Data type:         32 bit float (little endian)
  Data layout:       [ -0 +1 +2 +3 ]
  Data scaling:      offset = 0, multiplier = 1
  Comments:          FSL5.0
  Transform:                    1           0          -0       -90.6
                               -0           1           0        -126
                               -0           0           1         -72
                                0           0           0           1

hayashis@haswell:~/git/fibernavigator/bin(master) $ ./fibernavigator ~/Downloads/dwi.nii.gz 
[11:49:12] Initializing OpenGL
[11:49:18] Loading anatomy
Segmentation fault (core dumped)
```

I am not sure if this is expected or not, but it should at least open UI with some error message?

**Comment by chamberm** [comment]
Hi,

Unfortunately no, the Fibernavigator only opens 3D images.

Actually, the only 4D option is to use the resting-state panel load button after having pre-loaded a 3D map of the same size of your DWIs.

I encourage you to have a look at one of our video tutorials to see what are the allowed file formats.

Maxime

**Comment by jchoude** [comment]
Hi,

regarding the UI with an error message, it does so if you try to load the DWI dataset once the application is open.

The thing is, most of the current users don't use the command line loading mecanism, so it is not frequently tested. I guess it would be relatively easy to add a check and print a message instead of simply crashing.
