### ISSUE TITLE
Issues with nifti as unsupported format - scale values, matrix size?

### ISSUE THREAD

**Issue by franciscofritz** [scilus/fibernavigator#225]
Hey,

I have a small question. I am using MDT and trying to open the nifti files in fibernavigator. However, in both Windows and Linux versions the same error appears: "ERROR: Unsupported file format
Segmentation fault (core dumped)". Is it because the size of my images? Intensity scale values? I am using images of ex-vivo brains from a range of 1mm isotropic (~ 170 x 150 x 160 voxels) and 400um isotropic. 

Best,
F.

**Comment by chamberm** [comment]
Hi Francisco,

thanks you for you interest in the tool. Could you provide us with the datatype of your dataset (e.g., float32, 64, int16 etc.). It could very well be that you are trying to open an unsupported format (float64 if I'm correct). You could however try the most up to date FiberNavigator version here and see if the problem persists:

https://github.com/chamberm/fibernavigator/releases

Best,
Maxime

**Comment by franciscofritz** [comment]
Hey!

Thanks for the answer. Ehmm... no. It is still complaining about the unsupported format. I will try to convert to float32 just in case and try again.

**Comment by chamberm** [comment]
Hi,

I think the last error comes from a mismatch between windows version (the recent build was done on Windows 10). the ones before were done on Windows 8 if I'm correct.

also did you have a look at your datatypes? 
Max

**Comment by franciscofritz** [comment]
Indeed! I am using Windows 8 (and not option to update it to Windows 10 it seems).

And yes, I asked Robbert about this issue and he mentioned to me that the use of double_float precision calculations during fitting or sampling saves automatically the results also in float64 precision. The only thing I could try now is to convert the maps of interest in float32 or similar.

F.

**Comment by franciscofritz** [comment]
Ok, it worked to convert from Float64 to Float32 in the meanwhile. Now I am trying to guess what to do with the peaks (which I really don't get the asked format). Should it be a 4D nifti with the coordinates of the first eigenvector? Should be converted then in phi/theta coordinates? It doesn't like it when I try to open the first eigenvector.

F
