### ISSUE TITLE
Crash on Windows and Mac when loading .tck file

### ISSUE THREAD

**Issue by vravano** [scilus/fibernavigator#226]
Hi all,

Fibernav crashes both on Windows and OS X when trying to load a track file.
Our track file is composed by 10 million iFOD2 streamlines obtained with Mrtrix.

Do you have any clue about this ? Anything we are doing wrong?
Thank you for your help,

Veronica

**Comment by chamberm** [comment]
Hi Veronica,

Which version of the FiberNavigator are you using? It could be that the file is too big to be handled by the widows32 version (we do however have a win64 version built on windows10). I'm unsure about the OS X crash however.

Link here: https://github.com/chamberm/fibernavigator

If you manage to open the file, I'd suggest to downsample the # of streamlines before playing with ROIs (there should be a slider that allows you to do this step in the Properties panel of the fibers).

Also, just for sanity check, are you able to load a subset of the tractogram ? (i.e., lets say 500k ?) If its for visualization only that should do the trick. 

Maxime
